only support python2's meta-hdc
Issue: LIN9-6613

There are two issues with python3-device-cloud in WRL9, so we decide to only
support python-device-cloud:
* The WRL9's python3 only searches site-packages in /usr/lib, no /usr/lib64,
  so there is an error:
  ImportError: No module named 'pkg_resources'

  There is a patch on upsream, but not easy to backport, see oe-core's
  f60d261b682f1526fb7a754c425300954ef85042.

* python3-device-cloud conflicts with python-device-cloud.

Based on the two problems, we only support python2.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>