wrlinux-image-glibc-core.bb: only set NO_RECOMMENDATIONS for do_rootfs
Issue: LIN9-2062

Fixed:
$ bitbake wrlinux-image-glibc-core -cpopulate_sdk
$ bitbake wrlinux-image-glibc-core -ctestsdk
[snip]
/path/to/sysroots/core2-64-wrs-linux/usr/include/bits/local_lim.h:38:26: fatal error: linux/limits.h: No such file or directory
 #include <linux/limits.h>
[snip]

This is because linux-libc-headers-dev is not installed on sdk, this
patch can make it install when do_populate_sdk, and the problem will be
fixed.

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>