Revert "wr-self-hosted: create a new packagegroup"
This reverts commit 6694a6260625e2ccc54ae18aaac61c149aa51a6c.

This change resulted in world builds failing with the error:
   ERROR: packagegroup-wr-self-hosted-1.0-r13 do_packagedata:
   The recipe packagegroup-wr-self-hosted is trying to install
   files into a shared area when those files already exist.
   ...
   Please verify which recipe should provide the above files.

Signed-off-by: Randy MacLeod <Randy.MacLeod@windriver.com>