packagegroup-busybox-replacement.bb: remove sysklogd
Issue: CGP9-134

Fixed:
Computing transaction...error: Can't install packagegroup-busybox-replacement-1.0-r0@all: unable to install provider for sysklogd:
error:     sysklogd-1.5.1-r0@i586 is conflicted by rsyslog-8.22.0-r0@i586

rsyslog now conflicts with sysklogd and busybox-syslog, the rsyslog or
sysklogd will be installed by:
VIRTUAL-RUNTIME_syslog ?= "${@bb.utils.contains('INCOMPATIBLE_LICENSE', 'GPLv3', 'sysklogd', 'rsyslog', d)}"

Signed-off-by: Robert Yang <liezhi.yang@windriver.com>